--compat-options filename
--restrict-filename
--embed-metadata
--no-simulate
--verbose
--cookies /home/cameron/txt/cookies.txt
--cookies /home/cameron/txt/cookies.firefox-private.txt
--js-runtimes node
--js-runtimes node:/home/linuxbrew/.linuxbrew/bin/node
--js-runtimes node:/home/linuxbrew/.linuxbrew/Cellar/node/24.8.0/bin/node
--remote-components ejs:github
